# Generated by Django 5.1.3 on 2024-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarena_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulasan',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
